- project:
    templates:
      - openstack-cover-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - check-requirements
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - legacy-tricircle-dsvm-functional
        - legacy-tricircle-dsvm-multiregion
    gate:
      jobs:
        - legacy-tricircle-dsvm-functional
        - legacy-tricircle-dsvm-multiregion
